M48
; DRILL file {KiCad 8.0.1} date 2024-07-15T10:08:49+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-07-15T10:08:49+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.500
%
G90
G05
T1
X157.593Y-93.402
T2
X120.143Y-38.72
X120.143Y-73.01
X156.973Y-73.01
X156.973Y-45.07
T3
X126.493Y-85.202
X150.693Y-85.202
M30
